name: Upload Website

on:
  push:
    branches:
      - main
    paths:
      - 'public/**' # only run on changes to public

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Sync index.html'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --include "index.html" --cache-control max-age=0,no-cache,no-store,must-revalidate
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2' # region bucket was created in
          SOURCE_DIR: 'public'
